// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModaAyse.Repository;

#nullable disable

namespace ModaAyse.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250109174127_initial_duzenleme")]
    partial class initial_duzenleme
	{
	}
}
